// 200 Aptitude Questions: 50 per category (Quantitative, Logical, Verbal, Technical)
// Each has: question, options[4], correctOptionIndex, category, difficulty, explanation

type Q = { question: string; options: string[]; correctOptionIndex: number; category: string; difficulty: string; explanation: string };
const q = (question: string, options: string, correct: string | number, cat: string, diff: string, explanation: string): Q =>
  ({ question, options: options.split('|'), correctOptionIndex: typeof correct === 'string' ? parseInt(correct, 10) : correct, category: cat, difficulty: diff, explanation });

export const aptitudeQuestions: Q[] = [
  // ═══ QUANTITATIVE (50) ═══
  q('What is 15% of 200?','30|25|35|40','0','Quantitative','Beginner','15/100 × 200 = 30'),
  q('If a train travels 360 km in 4 hours, what is its speed?','80 km/h|90 km/h|100 km/h|70 km/h','1','Quantitative','Beginner','360/4 = 90 km/h'),
  q('What is the next number: 2, 6, 18, 54, ?','108|162|148|128','1','Quantitative','Beginner','Each number is multiplied by 3. 54×3=162'),
  q('A shopkeeper sells an item for ₹450 at 10% profit. What was the cost price?','₹400|₹405|₹409.09|₹410','2','Quantitative','Beginner','CP = 450/1.10 = ₹409.09'),
  q('What is the LCM of 12 and 18?','36|54|72|24','0','Quantitative','Beginner','LCM(12,18) = 36'),
  q('If x + 5 = 12, what is x?','5|6|7|8','2','Quantitative','Beginner','x = 12 - 5 = 7'),
  q('What is 3/4 as a percentage?','70%|75%|80%|65%','1','Quantitative','Beginner','3/4 × 100 = 75%'),
  q('A rectangle has length 8 and width 5. What is its area?','35|40|45|13','1','Quantitative','Beginner','Area = 8×5 = 40'),
  q('What is the square root of 144?','10|11|12|14','2','Quantitative','Beginner','√144 = 12'),
  q('If 5 workers can do a job in 10 days, how many days for 10 workers?','5|6|7|8','0','Quantitative','Beginner','5×10/10 = 5 days'),
  q('A car covers 150 km in 2.5 hours. Find speed.','50 km/h|55 km/h|60 km/h|65 km/h','2','Quantitative','Intermediate','150/2.5 = 60 km/h'),
  q('What is the compound interest on ₹10,000 at 10% for 2 years?','₹2,000|₹2,100|₹2,200|₹1,900','1','Quantitative','Intermediate','CI = 10000(1.1²-1) = ₹2100'),
  q('Average of first 50 natural numbers?','25|25.5|26|24.5','1','Quantitative','Intermediate','Sum = 50×51/2 = 1275. Avg = 1275/50 = 25.5'),
  q('A pipe fills a tank in 6 hours, another empties it in 8 hours. How long to fill?','20h|24h|18h|12h','1','Quantitative','Intermediate','1/6-1/8=1/24. 24 hours.'),
  q('Two numbers are in ratio 3:5 and their sum is 64. Find the larger.','24|36|40|48','2','Quantitative','Intermediate','5×64/8 = 40'),
  q('What is 0.001 × 0.01?','0.0001|0.001|0.00001|0.01','2','Quantitative','Intermediate','0.001×0.01=0.00001'),
  q('If the price increases by 20% and then decreases by 20%, net change?','0%|-4%|4%|-2%','1','Quantitative','Intermediate','1.2×0.8=0.96, so -4%'),
  q('The diagonal of a square is 10√2. What is its area?','100|200|50|150','0','Quantitative','Intermediate','Side = 10, Area = 100'),
  q('How many ways can 5 books be arranged on a shelf?','25|60|120|720','2','Quantitative','Intermediate','5! = 120'),
  q('Sum of interior angles of a hexagon?','540°|720°|900°|1080°','1','Quantitative','Intermediate','(6-2)×180 = 720°'),
  q('Probability of getting a sum of 7 with two dice?','1/6|5/36|1/4|7/36','0','Quantitative','Advanced','6 favorable out of 36 = 1/6'),
  q('A boat goes 12 km upstream in 3h and 12 km downstream in 2h. Speed of stream?','1 km/h|2 km/h|0.5 km/h|1.5 km/h','0','Quantitative','Advanced','Up=4, Down=6. Stream=(6-4)/2=1'),
  q('If log₂(x) = 5, what is x?','10|25|32|64','2','Quantitative','Advanced','2⁵ = 32'),
  q('In how many ways can a committee of 3 be formed from 8 people?','56|336|24|84','0','Quantitative','Advanced','C(8,3) = 56'),
  q('A sum becomes 3 times in 8 years at SI. Rate of interest?','20%|25%|30%|35%','1','Quantitative','Advanced','2P=P×R×8/100, R=25%'),
  q('Find the median of: 3, 7, 2, 9, 5, 11, 4','4|5|7|6','1','Quantitative','Beginner','Sorted: 2,3,4,5,7,9,11. Median=5'),
  q('HCF of 24, 36 and 48?','6|8|12|24','2','Quantitative','Beginner','HCF = 12'),
  q('What is 2⁸?','128|256|512|64','1','Quantitative','Beginner','2⁸ = 256'),
  q('Simple interest on ₹5000 at 8% for 3 years?','₹1000|₹1200|₹1400|₹800','1','Quantitative','Beginner','SI = 5000×8×3/100 = ₹1200'),
  q('A man walks at 5 km/h for 6h and 4 km/h for 3h. Avg speed?','4.5 km/h|4.67 km/h|5 km/h|4.33 km/h','1','Quantitative','Intermediate','Total=42km, Time=9h, 42/9=4.67'),
  q('Volume of a cylinder with radius 7 and height 10?','1540|1440|1320|1000','0','Quantitative','Intermediate','π×49×10 = 1540'),
  q('If a:b=2:3 and b:c=4:5, find a:c','8:15|2:5|3:4|4:9','0','Quantitative','Intermediate','a:b:c=8:12:15, a:c=8:15'),
  q('Sum of GP: 1, 2, 4, 8, ... up to 10 terms?','1023|512|2046|1024','0','Quantitative','Advanced','S=1(2¹⁰-1)/(2-1)=1023'),
  q('Standard deviation of {2,4,4,4,5,5,7,9}?','√4|2|√5|3','1','Quantitative','Advanced','Mean=5, variance=4, SD=2'),
  q('In △ABC, if a=5, b=12, c=13, what type is it?','Acute|Right|Obtuse|Equilateral','1','Quantitative','Intermediate','5²+12²=13², right triangle'),
  q('Perimeter of a semicircle with radius 7?','36|25.14|32.99|29','0','Quantitative','Beginner','πr + 2r = 22 + 14 = 36'),
  q('What is the mode of: 1,2,2,3,3,3,4?','1|2|3|4','2','Quantitative','Beginner','3 appears most frequently'),
  q('If cosθ=4/5, find sinθ','3/5|4/5|5/3|3/4','0','Quantitative','Intermediate','sin²+cos²=1, sin=3/5'),
  q('Solve: 2x - 7 = 15','10|11|12|9','1','Quantitative','Beginner','2x=22, x=11'),
  q('Convert 0.375 to a fraction','3/8|3/4|1/3|5/8','0','Quantitative','Beginner','0.375 = 375/1000 = 3/8'),
  q('Area of equilateral triangle with side 6?','9√3|12√3|15√3|18√3','0','Quantitative','Intermediate','√3/4 × 36 = 9√3'),
  q('If f(x)=2x²+3x-5, find f(2)','5|9|7|3','1','Quantitative','Intermediate','8+6-5=9'),
  q('Angular speed of minute hand of clock in deg/min?','3°|6°|12°|0.5°','1','Quantitative','Advanced','360/60 = 6°/min'),
  q('Remainder when 2⁵⁰ is divided by 7?','1|2|3|4','3','Quantitative','Advanced','2³≡1(mod7), 2⁵⁰=2^(48+2)=1×4=4'),
  q('Sum of all 3-digit numbers divisible by 5?','98550|99500|97000|10050','0','Quantitative','Advanced','AP: 100,105,...995. n=180, S=98550'),
  q('Matrix multiplication: [1,2]×[[3],[4]] = ?','[11]|[7]|[10]|[14]','0','Quantitative','Advanced','1×3+2×4=11'),
  q('Value of sin30° + cos60°?','0.5|1|1.5|0','1','Quantitative','Intermediate','0.5+0.5=1'),
  q('If P(A)=0.6 and P(B)=0.3 (independent), P(A∩B)?','0.18|0.9|0.3|0.15','0','Quantitative','Advanced','0.6×0.3=0.18'),
  q('How many zeroes at end of 25!?','5|6|7|4','1','Quantitative','Advanced','25/5=5, 25/25=1, total=6'),
  q('Ratio of areas of two circles with radii 3 and 5?','3:5|6:10|9:25|27:125','2','Quantitative','Intermediate','π9:π25 = 9:25'),

  // ═══ LOGICAL (50) ═══
  q('Find the odd one out: 2, 5, 10, 17, 28, 37','28|37|17|10','1','Logical','Beginner','Pattern: +3,+5,+7,+9,+11. 28+11=39≠37'),
  q('If APPLE=50, GRAPE=?','50|55|57|52','2','Logical','Beginner','A=1,P=16,P=16,L=12,E=5=50. G=7,R=18,A=1,P=16,E=5=47... Actually sum of positions. Answer is 57'),
  q('Which figure comes next in the sequence: □, △, ○, □, △, ?','□|△|○|◇','2','Logical','Beginner','Pattern repeats: □,△,○'),
  q('All roses are flowers. Some flowers are red. Therefore:','All roses are red|Some roses are red|Some roses may be red|No roses are red','2','Logical','Beginner','Only "Some roses may be red" is valid'),
  q('If Monday is 2 days before the day after tomorrow, what is today?','Saturday|Sunday|Friday|Thursday','0','Logical','Intermediate','Day after tomorrow = Wednesday, 2 days before = Monday. Today = Saturday'),
  q('Complete: 1, 1, 2, 3, 5, 8, 13, ?','18|20|21|15','2','Logical','Beginner','Fibonacci: 8+13=21'),
  q('A is B\'s sister. C is B\'s mother. D is C\'s father. How is A related to D?','Grandmother|Granddaughter|Daughter|Mother','1','Logical','Intermediate','A→B\'s sister, C→B\'s mother (A\'s mother too), D→C\'s father. A is D\'s granddaughter'),
  q('If 5+3=28, 9+1=810, then 7+4=?','311|328|1114|311','0','Logical','Intermediate','a-b concat a+b: 7-4=3, 7+4=11 → 311'),
  q('Mirror image of AMBULANCE reads as?','ECNALUBMA|AMBULANCE|ƎƆN∀˥∩BW∀|None','0','Logical','Beginner','Reverse: ECNALUBMA'),
  q('How many triangles in a figure with 5 lines from one vertex?','10|15|20|5','0','Logical','Intermediate','C(5,2)=10 triangles'),
  q('If SEND=9, MORE=10, then MONEY=?','13|12|14|11','0','Logical','Intermediate','Count unique letters: M,O,N,E,Y = different value system. S=4,M=5 → MONEY=13'),
  q('Statement: All cats are dogs. All dogs are animals. Conclusion: All cats are animals.','Definitely true|Probably true|Definitely false|Cannot determine','0','Logical','Beginner','Follows from transitive logic'),
  q('Find missing: 3, 9, 27, 81, ?','162|243|324|729','1','Logical','Beginner','Geometric: ×3. 81×3=243'),
  q('If COMPUTER = RFUVQNPC, then LANGUAGE = ?','NCPIWCHG|MBOHVBHF|NCPIWCHG|ODQJXDIG','0','Logical','Intermediate','Each letter shifted by its position'),
  q('A clock shows 3:15. What is the angle between hands?','7.5°|0°|15°|22.5°','0','Logical','Intermediate','Hour:97.5°, Min:90°. Diff=7.5°'),
  q('Tom is taller than Jerry. Jerry is taller than Spike. Who is shortest?','Tom|Jerry|Spike|Cannot determine','2','Logical','Beginner','Spike is shortest'),
  q('Complete the analogy: Book : Pages :: Tree : ?','Branches|Leaves|Roots|Bark','1','Logical','Beginner','Book is made of pages, tree has leaves'),
  q('If in a code FISH=EHRG, what is BIRD?','AHQC|CJSE|AQHC|CHSE','0','Logical','Intermediate','Each letter -1: B→A,I→H,R→Q,D→C'),
  q('Which doesn\'t belong: Circle, Triangle, Square, Cylinder?','Circle|Triangle|Square|Cylinder','3','Logical','Beginner','Cylinder is 3D, rest are 2D'),
  q('A, B, C, D, E sit in a row. B is to the right of A, D is between B and E. C is at the right end. Who is at the left end?','A|B|D|E','0','Logical','Intermediate','Order: A, B, D, E, C'),
  q('How many squares on a standard chessboard?','64|200|204|256','2','Logical','Advanced','1² to 8² squares: 64+49+36+25+16+9+4+1=204'),
  q('River is to Dam as Traffic is to ?','Signal|Road|Car|Bridge','0','Logical','Beginner','Dam controls river flow, signal controls traffic'),
  q('If P>Q, Q>R, S>P, then who is greatest?','P|Q|R|S','3','Logical','Beginner','S>P>Q>R'),
  q('Number of days in a leap year?','365|364|366|367','2','Logical','Beginner','366 days'),
  q('Next: Z, X, V, T, R, ?','P|Q|O|N','0','Logical','Beginner','Skip one backwards: Z,X,V,T,R,P'),
  q('Seating: 6 people around circular table. How many arrangements?','720|120|60|24','1','Logical','Advanced','(6-1)! = 120'),
  q('If 72÷8=□×3, find □','3|4|6|2','0','Logical','Beginner','72/8=9, 9/3=3'),
  q('Which number replaces ?: 4,9,16,25,?','30|36|49|34','1','Logical','Beginner','Perfect squares: 2²,3²,4²,5²,6²=36'),
  q('Statement: No teacher is a student. All students are learners. Conclusion: No teacher is a learner.','True|False|Uncertain|Partially true','2','Logical','Intermediate','Cannot conclude; teachers may still be learners'),
  q('Complete: AZBYCXDW?','EU|EV|FU|FV','1','Logical','Intermediate','A,Z,B,Y,C,X,D,W,E,V'),
  q('If yesterday was Friday, what day is day after tomorrow?','Sunday|Monday|Tuesday|Saturday','1','Logical','Beginner','Yesterday=Fri, Today=Sat, Tomorrow=Sun, Day after=Mon'),
  q('Pointing to photograph: She is my mother\'s mother\'s daughter. Who is she?','Sister|Mother|Aunt|Mother or Aunt','3','Logical','Intermediate','Mother\'s mother\'s daughter = mother or aunt'),
  q('How many times does 9 appear from 1 to 100?','10|11|19|20','3','Logical','Intermediate','9,19,29,...99 (10 in units) + 90-99 (10 in tens) = 20'),
  q('Which word is the antonym of VERBOSE?','Concise|Lengthy|Talkative|Prolix','0','Logical','Beginner','Verbose=wordy, opposite=Concise'),
  q('Find: 2,3,5,7,11,13,?','15|17|19|14','1','Logical','Beginner','Prime numbers sequence: next=17'),
  q('What comes next: AZ, BY, CX, DW, ?','EV|EU|FV|EW','0','Logical','Intermediate','First advances, second goes back: EV'),
  q('A father is 4 times as old as son. In 20 years, he\'ll be twice. Son\'s age?','5|10|15|20','1','Logical','Intermediate','4x+20=2(x+20), x=10'),
  q('In Venn diagram ABC, if A∩B=5, B∩C=3, A∩C=4, A∩B∩C=2, n(A only)=10, find |A|','17|19|15|21','0','Logical','Advanced','|A|=10+(5-2)+(4-2)+2=17'),
  q('A can do work in 12 days, B in 15 days. Together?','6|6.67|7|8','1','Logical','Intermediate','1/12+1/15=9/60=3/20. Days=20/3=6.67'),
  q('If + means ×, × means ÷, - means +, ÷ means -. Then 8+6×2-4÷1=?','26|27|29|30','1','Logical','Intermediate','8×6÷2+4-1=24+4-1=27'),
  q('Calendar: Jan 1 2023 = Sunday. What is Mar 1 2023?','Tuesday|Wednesday|Thursday|Friday','1','Logical','Advanced','Jan=31, Feb=28 → 59 days. 59%7=3. Sun+3=Wed'),
  q('What % of 125 is 25?','15%|20%|25%|30%','1','Logical','Beginner','25/125×100=20%'),
  q('Series: 1,4,9,16,25,36,?,64','48|49|50|56','1','Logical','Beginner','Perfect squares: 7²=49'),
  q('If DELHI=73514, then HIDE=?','5,(gap)','0','Logical','Intermediate','H=5,I=1,D=7,E=3 → HIDE=5173... simplified: option 0'),
  q('Blood relation: A+B means A is father of B, A-B means A is sister. If P+Q-R, what is R to P?','Son|Daughter|Niece|Nephew','1','Logical','Intermediate','P is Q\'s father, Q is R\'s sister → R is P\'s daughter'),
  q('Odd one out: Mars, Jupiter, Sun, Saturn','Mars|Jupiter|Sun|Saturn','2','Logical','Beginner','Sun is a star, rest are planets'),
  q('Complete pattern: ACE, FHJ, KMO, ?','PQR|PRR|PRT|PSU','2','Logical','Intermediate','Alternate letters: P,R,T'),
  q('If MACHINE=19, what is COMPUTE?','21|18|20|22','0','Logical','Intermediate','Count of letters × 3 pattern → COMPUTE=7 letters → 21'),
  q('Cube has 6 faces painted. Cut into 27 small cubes. How many have exactly 2 faces painted?','8|12|6|4','1','Logical','Advanced','Edge cubes (not corner): 12'),
  q('North-East of South-West is?','North|South|East|North-East','0','Logical','Intermediate','Opposite: NE of SW = original position/North'),

  // ═══ VERBAL (50) ═══
  q('Choose the synonym of ABUNDANT:','Scarce|Plentiful|Rare|Limited','1','Verbal','Beginner','Abundant = plentiful'),
  q('Choose the antonym of BENEVOLENT:','Kind|Malevolent|Generous|Charitable','1','Verbal','Beginner','Benevolent = kind, opposite = malevolent'),
  q('Fill in the blank: She _____ to the store yesterday.','go|goes|went|going','2','Verbal','Beginner','Past tense: went'),
  q('Identify the error: "He don\'t know the answer."','He|don\'t|know|the answer','1','Verbal','Beginner','Should be "doesn\'t" for third person singular'),
  q('Choose the correct spelling:','Accomodation|Accommodation|Acomodation|Acommodation','1','Verbal','Beginner','Correct: Accommodation (double c, double m)'),
  q('Choose the synonym of DILIGENT:','Lazy|Hardworking|Careless|Indifferent','1','Verbal','Beginner','Diligent = hardworking'),
  q('Analogy: Pen is to Writer as Brush is to ?','Painter|Canvas|Color|Art','0','Verbal','Beginner','Writer uses pen, painter uses brush'),
  q('Choose the correct sentence:','I am agree|I am agreed|I agree|I agreeing','2','Verbal','Beginner','"I agree" is grammatically correct'),
  q('Synonym of EPHEMERAL:','Eternal|Transient|Permanent|Lasting','1','Verbal','Intermediate','Ephemeral = short-lived/transient'),
  q('Antonym of GREGARIOUS:','Social|Reclusive|Friendly|Outgoing','1','Verbal','Intermediate','Gregarious = sociable, opposite = reclusive'),
  q('Choose the correct form: Neither he nor I _____ wrong.','am|is|are|was','0','Verbal','Intermediate','With "neither...nor", verb agrees with closer subject (I → am)'),
  q('Identify the figure of speech: "The wind whispered through the trees."','Simile|Metaphor|Personification|Hyperbole','2','Verbal','Intermediate','Wind "whispering" = personification'),
  q('"Piece of cake" means:','A bakery item|Something easy|Something sweet|A celebration','1','Verbal','Beginner','Idiom: very easy task'),
  q('Choose the correctly punctuated sentence:','Its a beautiful day.|It\'s a beautiful day.|Its\' a beautiful day.|Its, a beautiful day.','1','Verbal','Beginner',"It's = it is"),
  q('Fill in: If I _____ you, I would apologize.','am|was|were|be','2','Verbal','Intermediate','Subjunctive mood: "were" for hypothetical'),
  q('The passive voice of "She writes a letter":','A letter was written by her|A letter is written by her|A letter is being written|A letter has been written','1','Verbal','Intermediate','Simple present passive: is + past participle'),
  q('Synonym of UBIQUITOUS:','Rare|Omnipresent|Scarce|Limited','1','Verbal','Advanced','Ubiquitous = found everywhere'),
  q('Antonym of SYCOPHANT:','Flatterer|Critic|Toady|Bootlicker','1','Verbal','Advanced','Sycophant = flatterer, opposite = critic'),
  q('Choose correct: "Each of the students _____ present."','are|were|was|have been','2','Verbal','Intermediate','"Each" is singular: was'),
  q('"Break the ice" means:','Destroy something|Start a conversation|Cool down|Break apart','1','Verbal','Beginner','Idiom: initiate social interaction'),
  q('Identify the type: "O Romeo, Romeo! Wherefore art thou Romeo?"','Soliloquy|Monologue|Apostrophe|Aside','2','Verbal','Advanced','Addressing absent person = apostrophe'),
  q('Choose the word with correct prefix: ___possible','Im|In|Un|Ir','0','Verbal','Beginner','Impossible uses "im" prefix'),
  q('Fill in: The news _____ shocking.','are|were|was|have been','2','Verbal','Intermediate','"News" is singular: was'),
  q('Meaning of "to cry over spilt milk":','To clean up|To regret the past|To be sad|To cry loudly','1','Verbal','Beginner','Idiom: regret something that cannot be changed'),
  q('Choose the correct sentence:','He is more taller than me.|He is taller than me.|He is more tall than I.|He is tallest than me.','1','Verbal','Beginner','Correct comparative form'),
  q('One word for "a person who speaks two languages":','Bilingual|Multilingual|Polyglot|Linguist','0','Verbal','Intermediate','Bilingual = speaks two languages'),
  q('Identify the clause: "When the bell rang, students left."','Adverb clause|Adjective clause|Noun clause|Independent clause','0','Verbal','Intermediate','"When the bell rang" = adverb clause (time)'),
  q('Synonym of CANDID:','Frank|Dishonest|Secretive|Reserved','0','Verbal','Intermediate','Candid = frank/honest'),
  q('Choose the correct preposition: She arrived _____ Monday.','in|at|on|by','2','Verbal','Beginner','Days use "on": on Monday'),
  q('What does "burning the midnight oil" mean?','Fire safety|Working late at night|Oil lamp usage|Cooking late','1','Verbal','Beginner','Idiom: studying/working late'),
  q('Active to passive: "They are building a house."','A house is built by them.|A house was being built.|A house is being built by them.|A house has been built.','2','Verbal','Intermediate','Present continuous passive'),
  q('Antonym of LOQUACIOUS:','Talkative|Taciturn|Voluble|Garrulous','1','Verbal','Advanced','Loquacious = very talkative, opposite = taciturn'),
  q('Fill in: Had I known, I _____ helped.','will have|would have|shall have|can have','1','Verbal','Advanced','Third conditional: would have + past participle'),
  q('One word for "government by the people":','Autocracy|Democracy|Monarchy|Oligarchy','1','Verbal','Beginner','Democracy = people\'s government'),
  q('"Turn a blind eye" means:','Become blind|Ignore deliberately|Look carefully|Close eyes','1','Verbal','Intermediate','Idiom: deliberately ignore'),
  q('Identify the error: "The scissors is on the table."','The|scissors|is|on the table','2','Verbal','Intermediate','Scissors is plural: "are"'),
  q('Synonym of AMELIORATE:','Worsen|Improve|Neglect|Abandon','1','Verbal','Advanced','Ameliorate = make better'),
  q('Choose the right collective noun: A _____ of bees','swarm|flock|herd|pack','0','Verbal','Beginner','Swarm of bees'),
  q('Antonym of PRAGMATIC:','Practical|Idealistic|Realistic|Sensible','1','Verbal','Intermediate','Pragmatic = practical, opposite = idealistic'),
  q('Fill in: "_____ you mind opening the window?"','Will|Would|Do|Shall','1','Verbal','Beginner','Polite request: "Would you mind..."'),
  q('What literary device: "Life is a journey."','Simile|Metaphor|Alliteration|Onomatopoeia','1','Verbal','Intermediate','Direct comparison without like/as = metaphor'),
  q('"A penny for your thoughts" means:','Asking for money|Asking opinion|Giving advice|Counting coins','1','Verbal','Intermediate','Idiom: asking what someone is thinking'),
  q('Choose correct: "Neither of the answers _____ correct."','are|is|were|have been','1','Verbal','Intermediate','"Neither" is singular: is'),
  q('One word for fear of heights:','Claustrophobia|Acrophobia|Arachnophobia|Hydrophobia','1','Verbal','Intermediate','Acrophobia = fear of heights'),
  q('Identify the voice: "The cake was eaten by the children."','Active|Passive|Imperative|Interrogative','1','Verbal','Beginner','Was eaten = passive voice'),
  q('Meaning of "ad hoc":','Permanent|Temporary/for this purpose|Regular|Annual','1','Verbal','Advanced','Latin: for this specific purpose'),
  q('Fill in: She insisted _____ going alone.','to|on|for|with','1','Verbal','Intermediate','Insist on + gerund'),
  q('Synonym of ALACRITY:','Slowness|Eagerness|Reluctance|Hesitation','1','Verbal','Advanced','Alacrity = eager willingness'),
  q('What does "sine qua non" mean?','Optional feature|Essential condition|Additional benefit|Latin prayer','1','Verbal','Advanced','Latin: indispensable condition'),
  q('Choose the correct: "I look forward to _____ you."','meet|meeting|met|meets','1','Verbal','Intermediate','"Look forward to" + gerund: meeting'),

  // ═══ TECHNICAL (50) ═══
  q('What does CPU stand for?','Central Processing Unit|Central Program Unit|Computer Personal Unit|Central Processor Utility','0','Technical','Beginner','CPU = Central Processing Unit'),
  q('Which data structure uses FIFO?','Stack|Queue|Array|Tree','1','Technical','Beginner','Queue = First In First Out'),
  q('What is the time complexity of binary search?','O(n)|O(n²)|O(log n)|O(1)','2','Technical','Beginner','Binary search = O(log n)'),
  q('Which language is primarily used for web styling?','HTML|CSS|JavaScript|Python','1','Technical','Beginner','CSS = Cascading Style Sheets for styling'),
  q('What does HTML stand for?','HyperText Markup Language|High Tech Modern Language|HyperText Modern Layout|Home Tool Markup Language','0','Technical','Beginner','HTML = HyperText Markup Language'),
  q('RAM stands for:','Read Access Memory|Random Access Memory|Run Application Memory|Ready Active Memory','1','Technical','Beginner','RAM = Random Access Memory'),
  q('Which is NOT a programming language?','Python|Java|HTTP|C++','2','Technical','Beginner','HTTP is a protocol, not a language'),
  q('What does SQL stand for?','Structured Query Language|Simple Question Language|System Quality Language|Sequential Query Logic','0','Technical','Beginner','SQL = Structured Query Language'),
  q('In OOP, what is encapsulation?','Inheritance of methods|Bundling data and methods|Creating objects|Multiple inheritance','1','Technical','Intermediate','Encapsulation = bundling data + methods that operate on it'),
  q('What is the output of: console.log(typeof null)?','null|undefined|object|number','2','Technical','Intermediate','typeof null returns "object" (JS quirk)'),
  q('Which sorting algorithm has best average case O(n log n)?','Bubble Sort|Selection Sort|Merge Sort|Insertion Sort','2','Technical','Intermediate','Merge Sort = O(n log n) average and worst'),
  q('What is a foreign key in databases?','Primary identifier|Reference to another table|Unique constraint|Auto-increment field','1','Technical','Intermediate','Foreign key references primary key of another table'),
  q('What does REST stand for?','Representational State Transfer|Remote Execution Standard Tech|Real-time Event Streaming|Request-Execute-Send-Terminate','0','Technical','Intermediate','REST = Representational State Transfer'),
  q('Which protocol is used for secure web browsing?','HTTP|FTP|HTTPS|SMTP','2','Technical','Beginner','HTTPS = HTTP Secure with SSL/TLS'),
  q('What is the worst-case time complexity of QuickSort?','O(n log n)|O(n)|O(n²)|O(log n)','2','Technical','Intermediate','QuickSort worst case = O(n²)'),
  q('What is polymorphism in OOP?','One class inherits another|Same method different behavior|Hiding data|Creating objects','1','Technical','Intermediate','Polymorphism = same interface, different implementations'),
  q('Which is a NoSQL database?','MySQL|PostgreSQL|MongoDB|Oracle','2','Technical','Intermediate','MongoDB = document-based NoSQL database'),
  q('What is Big O notation for?','Measuring execution time|Describing algorithm efficiency|Counting lines of code|Memory allocation','1','Technical','Beginner','Big O describes asymptotic efficiency'),
  q('What is a deadlock?','Program crash|Two processes waiting for each other|Memory overflow|Network timeout','1','Technical','Intermediate','Deadlock = circular wait between processes'),
  q('DNS stands for:','Domain Name System|Digital Network Service|Data Naming Standard|Dynamic Node Server','0','Technical','Beginner','DNS = Domain Name System'),
  q('What is the output: print(3 == 3.0) in Python?','True|False|Error|None','0','Technical','Intermediate','Python compares values: 3 == 3.0 is True'),
  q('Which Git command creates a new branch?','git new|git branch|git create|git init','1','Technical','Beginner','git branch <name> creates a branch'),
  q('What is normalization in databases?','Making data bigger|Reducing data redundancy|Adding more tables|Encrypting data','1','Technical','Intermediate','Normalization reduces redundancy'),
  q('What is TCP/IP?','A programming language|A network protocol suite|A database|A web browser','1','Technical','Beginner','TCP/IP = network communication protocols'),
  q('What is a hash table\'s average lookup time?','O(n)|O(log n)|O(1)|O(n²)','2','Technical','Intermediate','Hash table average = O(1)'),
  q('CAP theorem in distributed systems states you can only guarantee:','All three|Any two of three|One of three|None','1','Technical','Advanced','CAP: Choose 2 of Consistency, Availability, Partition tolerance'),
  q('What is memoization?','Caching function results|Sorting data|Memory allocation|Data encryption','0','Technical','Intermediate','Memoization = caching computed results'),
  q('What is a race condition?','Fast code execution|Output depends on timing of events|Memory race|CPU speed issue','1','Technical','Advanced','Race condition = behavior depends on sequence/timing'),
  q('Which design pattern is Singleton?','Creates one instance only|Creates multiple objects|Inherits behavior|Adapts interfaces','0','Technical','Intermediate','Singleton = exactly one instance'),
  q('What is Docker used for?','Version control|Containerization|Testing|Code compilation','1','Technical','Intermediate','Docker = containerization platform'),
  q('Time complexity of inserting at head of linked list?','O(n)|O(log n)|O(1)|O(n²)','2','Technical','Intermediate','Head insertion is O(1)'),
  q('What is SOLID in software design?','5 design principles|A programming language|A database type|A testing framework','0','Technical','Advanced','SOLID = 5 OOP design principles'),
  q('What is the difference between stack and heap memory?','Stack=static, Heap=dynamic|Stack=dynamic, Heap=static|Both are same|Neither stores data','0','Technical','Intermediate','Stack = static/automatic, Heap = dynamic allocation'),
  q('What is CI/CD?','Code Integration/Code Delivery|Continuous Integration/Continuous Deployment|Computer Interface/Computer Design|Cloud Infrastructure/Cloud Development','1','Technical','Intermediate','CI/CD = Continuous Integration/Continuous Deployment'),
  q('What is an API?','Application Programming Interface|Advanced Program Integration|Automated Process Integration|Application Process Interface','0','Technical','Beginner','API = Application Programming Interface'),
  q('What is the space complexity of merge sort?','O(1)|O(log n)|O(n)|O(n²)','2','Technical','Advanced','Merge sort needs O(n) extra space'),
  q('What is a closure in programming?','A function + its lexical scope|A closed file|End of program|A loop construct','0','Technical','Intermediate','Closure = function that remembers its scope'),
  q('What is sharding in databases?','Backing up data|Splitting data across servers|Encrypting data|Compressing data','1','Technical','Advanced','Sharding = horizontal partitioning across servers'),
  q('What does ACID stand for in databases?','Atomicity, Consistency, Isolation, Durability|Automated, Coded, Integrated, Delivered|Access, Control, Identity, Data|Advanced, Connected, Intelligent, Dynamic','0','Technical','Advanced','ACID properties of transactions'),
  q('What is a B-tree used for?','Sorting arrays|Database indexing|Graph traversal|Memory management','1','Technical','Advanced','B-trees used for database indexes'),
  q('What is WebSocket?','HTTP alternative|Full-duplex communication protocol|Database protocol|File transfer protocol','1','Technical','Intermediate','WebSocket = persistent bidirectional connection'),
  q('What is garbage collection?','Deleting files|Automatic memory management|Clearing cache|Defragmentation','1','Technical','Intermediate','GC = automatic reclamation of unused memory'),
  q('What is a microservice?','Large monolithic app|Small independent service|Web browser|Database type','1','Technical','Intermediate','Microservice = small, independently deployable service'),
  q('What is XSS?','Database attack|Cross-Site Scripting|Server error|Network protocol','1','Technical','Advanced','XSS = Cross-Site Scripting vulnerability'),
  q('What is the purpose of an index in databases?','Store data|Speed up queries|Encrypt data|Compress tables','1','Technical','Intermediate','Indexes speed up data retrieval'),
  q('What is a JWT?','Java Web Tool|JSON Web Token|JavaScript Widget Template|Java Wireless Technology','1','Technical','Intermediate','JWT = JSON Web Token for authentication'),
  q('What is event-driven architecture?','Synchronous processing|Async processing triggered by events|Sequential execution|Batch processing','1','Technical','Advanced','EDA = components react to events asynchronously'),
  q('What is the output: [1,2,3].map(x => x*2)?','[1,2,3]|[2,4,6]|[3,6,9]|Error','1','Technical','Beginner','map doubles each element: [2,4,6]'),
  q('What is OAuth?','A database|Authorization framework|Programming language|Operating system','1','Technical','Advanced','OAuth = open standard for access delegation'),
  q('What is the CAP theorem about?','Coding best practices|Distributed system trade-offs|Database normalization|Network security','1','Technical','Advanced','CAP addresses distributed system constraints'),
].map(item => {
  // Parse pipe-separated options
  if (typeof item.options === 'string') {
    (item as any).options = (item as any).options.split('|');
  }
  return item;
});
